sudo: required
dist: xenial
language: go
go: "1.11"

branches:
  only:
  - master
  - /^v[0-9]/

jobs:
  - stage: Build and Deploy
    name: Build and Deploy to GitHub
    if: tag IS present
    before_script: skip
    script: make release "VERSION=$TRAVIS_TAG"
    deploy:
      provider: releases
      api_key: "$GITHUB_TOKEN"
      skip_cleanup: true
      overwrite: true
      file_glob: true
      file:
      - binaries/*
      name: $TRAVIS_TAG
      on:
        tags: true
        branch: master
        repo: $TRAVIS_REPO_SLUG
